config/routes.rb
Rails.application.routes.draw do
  get 'parametres', to: "parametres#index"
  post 'parametres', to: "parametres#save"

  devise_for :users #, controllers: { sessions: "users/sessions" }
  get 'scans', to: "scans#index"

  resources :livres do
    member do
      get :avatar
      post :avatar, to: :save_avatar
    end
      get ':isbn/get_datas', on: :collection, to: 'livres#get_datas'
  end

  resources :auteurs do
    get :autocomplete_auteur_nom, on: :collection
    get :fusion, on: :collection
    post :fusion, on: :collection, to: :choix_fusion
    post :fusionner, on: :collection
    member do
      get :avatar
      post :avatar, to: :save_avatar
    end
  end

  resources :editions do
    get :autocomplete_edition_nom, on: :collection
    get :fusion, on: :collection
    post :fusion, on: :collection, to: :fusionner
  end

  resources :genres do
    get :autocomplete_genre_nom, on: :collection
    get :fusion, on: :collection
    post :fusion, on: :collection, to: :fusionner
  end

  resources :emplacements do
    get :autocomplete_emplacement_nom, on: :collection
  end

  root 'livres#index'

end

app/models/genre.rb
class Genre < ActiveRecord::Base
	has_many :livres
	validates :nom, presence: true, uniqueness: true
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  before_action :set_genre, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:edit, :update, :destroy, :new, :fusion, :fusionner]
  before_filter :init

  def init
    @title = "Genres"
  end

  def autocomplete_genre_nom
    @genres = Genre.order(:nom).where("LOWER(nom) like LOWER(?)", "%#{params[:term]}%")
    respond_to do |format|
      format.html
      format.json { render json: @genres.map(&:nom) }
    end
  end

  # GET /genres
  # GET /genres.json
  def index
    @genres = Genre.order(:nom)
    @genre = Genre.new
  end

  # GET /genres/new
  def new
    @genre = Genre.new
  end

  # GET /genres/1/edit
  def edit
  end

  # POST /genres
  # POST /genres.json
  def create
    @genre = Genre.new(genre_params)
    if @genre.nom.present? && @genre.save
      flash[:notice] = "Genre \"#{@genre.nom}\" créé."
    else
      flash[:error] = "Genre \"#{@genre.nom}\" existe déjà."
    end
    redirect_to genres_path
  end

  # PATCH/PUT /genres/1
  # PATCH/PUT /genres/1.json
  def update
    if @genre.nom.present? && @genre.update(genre_params)
      flash[:notice] = "Genre \"#{@genre.nom}\" modifié."
    else
      flash[:error] = "Genre \"#{@genre.nom}\" existe déjà."
    end
    redirect_to genres_path
  end

  # DELETE /genres/1
  # DELETE /genres/1.json
  def destroy
    @genre.livres.each do |livre|
      livre.genre_id = nil
      livre.save
    end
    @genre.destroy
    respond_to do |format|
      format.html { redirect_to genres_url, notice: "Genre \"#{@genre.nom}\" a bien été supprimé." }
      format.json { head :no_content }
    end
  end

  def fusion
    @genres = Genre.order(:nom)
  end

  def fusionner
    liste = params["/genres/fusion"].select{|id,bool| bool=="1"}.map{|id,bool| id}
    genres = Genre.find(liste)
    id_to_keep = genres.first.id
    genres.each do |genre|
      if genre.id != id_to_keep
        Livre.where(genre_id: genre.id).each do |livre|
          livre.genre_id = id_to_keep
          livre.save
        end
        genre.destroy
      end 
    end
    redirect_to genres_url, notice: "Fusion effectuée."
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_genre
      @genre = Genre.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def genre_params
      params.require(:genre).permit(:nom)
    end

end

app/views/genres/_form.html.haml
= bootstrap_form_for @genre, layout: :horizontal do |f|
  - if @genre.errors.any?
    #error_explanation
      %h2= "#{pluralize(@genre.errors.count, "error")} prohibited this genre from being saved:"
      %ul
        - @genre.errors.full_messages.each do |msg|
          %li= msg

  = f.text_field :nom
  = f.submit 'Save', class: "btn"

app/views/genres/choix_fusion.html.haml
= bootstrap_form_for fusionner_genres_path, url: fusionner_genres_path do |f|
  %table.table.centree-mini
    %tr
      %td
        Choisir le genre à conserver
    - @genres.each_with_index do |genre, index|
      -if index % 2 == 0
        %tr
      %td
        = f.radio_button :master, genre.id, label: genre.nom, checked: index==0
        = f.hidden_field "ids[#{genre.id}]"
    %tr
      %td
        = f.submit "Valider", class: "btn"
      

app/views/genres/edit.html.haml
.centree-mini
  = render 'form'

app/views/genres/fusion.html.haml
= bootstrap_form_for(fusion_genres_path) do |f|
  %table.table.centree-mini
    %tr
      %td{colspan: 2}
        Choisir les genres à fusionner
    - @genres.each_with_index do |genre, index|
      -if index % 2 == 0
        %tr
      %td
        = f.check_box genre.id, label: genre.nom, id: "fusionner[#{genre.id}]"
    %tr
      %td{colspan: 2}
        = f.submit "Valider", class: "btn"
      

app/views/genres/index.html.haml
%table.table.centree-mini
  - if user_signed_in?
    %tr
      = bootstrap_form_for @genre do |f|
        %td
          = f.text_field :nom, placeholder: "Nouveau genre", hide_label: :true
        %td
          %button.btn.xs
            %span.glyphicon.glyphicon-plus
      %td{colspan: 2}
        = button_to "Fusionner des genres", fusion_genres_path, method: :get, class: "btn pull-right"
  - @genres.each_with_index do |genre, index|
    -if index%2==0
      %tr   
    %td= genre.nom
    %td
      - if user_signed_in?
        = button_to edit_genre_path(genre), method: :get, class: "btn pull-left" do
          .glyphicon.glyphicon-pencil
%br