config/routes.rb
Rails.application.routes.draw do
  get 'parametres', to: "parametres#index"
  post 'parametres', to: "parametres#save"

  devise_for :users #, controllers: { sessions: "users/sessions" }
  get 'scans', to: "scans#index"

  resources :livres do
    member do
      get :avatar
      post :avatar, to: :save_avatar
    end
      get ':isbn/get_datas', on: :collection, to: 'livres#get_datas'
  end

  resources :auteurs do
    get :autocomplete_auteur_nom, on: :collection
    get :fusion, on: :collection
    post :fusion, on: :collection, to: :choix_fusion
    post :fusionner, on: :collection
    member do
      get :avatar
      post :avatar, to: :save_avatar
    end
  end

  resources :editions do
    get :autocomplete_edition_nom, on: :collection
    get :fusion, on: :collection
    post :fusion, on: :collection, to: :fusionner
  end

  resources :genres do
    get :autocomplete_genre_nom, on: :collection
    get :fusion, on: :collection
    post :fusion, on: :collection, to: :fusionner
  end

  resources :emplacements do
    get :autocomplete_emplacement_nom, on: :collection
  end

  root 'livres#index'

end

app/models/edition.rb
class Edition < ActiveRecord::Base
	has_many :livres
	validates :nom, presence: true, uniqueness: true
end

app/controllers/editions_controller.rb
class EditionsController < ApplicationController
  before_action :set_edition, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:edit, :update, :destroy, :new, :fusion, :fusionner]
  before_filter :init

  def init
    @title = "Editions"
  end

  def autocomplete_edition_nom
    @editions = Edition.order(:nom).where("LOWER(nom) like LOWER(?)", "%#{params[:term]}%")
    respond_to do |format|
      format.html
      format.json { render json: @editions.map(&:nom) }
    end
  end

  # GET /editions
  # GET /editions.json
  def index
    @editions = Edition.order(:nom)
    @edition = Edition.new
  end

  # GET /editions/1
  # GET /editions/1.json
  def show
    @liste_by_auteur = @edition.livres.includes(:auteur).group_by{|livre| livre.auteur.nom}
  end

  # GET /editions/new
  def new
    @edition = Edition.new
  end

  # GET /editions/1/edit
  def edit
  end

  # POST /editions
  # POST /editions.json
  def create
    @edition = Edition.new(edition_params)
    if @edition.nom.present? && @edition.save
      flash[:notice] = "Edition \"#{@edition.nom}\" créé."
    else
      flash[:error] = @edition.errors.full_messages.join(',')
    end
    redirect_to editions_path
  end

  # PATCH/PUT /editions/1
  # PATCH/PUT /editions/1.json
  def update
    if @edition.nom.present? && @edition.update(edition_params)
      flash[:notice] = "Edition \"#{@edition.nom}\" modifié."
    else
      flash[:error] = @edition.errors.full_messages.join(',')
    end
    redirect_to editions_path
  end

  # DELETE /editions/1
  # DELETE /editions/1.json
  def destroy
    @edition.livres.each do |livre|
      livre.edition_id = nil
      livre.save
    end
    @edition.delete
    redirect_to editions_url, notice: 'Edition supprimée.'
  end

  def fusion
    @editions = Edition.order(:nom)
  end

  def fusionner
    liste = params["/editions/fusion"].select{|id,bool| bool=="1"}.map{|id,bool| id}
    editions = Edition.find(liste)
    id_to_keep = editions.first.id
    editions.each do |edition|
      if edition.id != id_to_keep
        Livre.where(edition_id: edition.id).each do |livre|
          livre.edition_id = id_to_keep
          livre.save
        end
        edition.destroy
      end 
    end
    redirect_to editions_url, notice: "Fusion effectuée."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_edition
      @edition = Edition.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def edition_params
      params.require(:edition).permit(:nom)
    end
end

app/views/editions/_form.html.haml
= bootstrap_form_for @edition, layout: :horizontal do |f|
  - if @edition.errors.any?
    #error_explanation
      %h2= "#{pluralize(@edition.errors.count, "error")} prohibited this edition from being saved:"
      %ul
        - @edition.errors.full_messages.each do |msg|
          %li= msg

  = f.text_field :nom
  = f.submit 'Save', class: "btn"

app/views/editions/fusion.html.haml
:javascript
  var lastChecked = null;

  $(document).ready(function() {
    var $chkboxes = $('input:checkbox');
    $chkboxes.click(function(e) {
      if(!lastChecked) {
          lastChecked = this;
          return;
      }

      if(e.shiftKey) {
          var start = $chkboxes.index(this);
          var end = $chkboxes.index(lastChecked);
          $chkboxes.slice(Math.min(start,end), Math.max(start,end)+ 1).attr('checked', lastChecked.checked);
      }
      lastChecked = this;
    });
  });

= bootstrap_form_for(fusion_editions_path) do |f|
  %table.table.centree-mini
    %tr
      %td{colspan: 2}
        Choisir les editions à fusionner
    - @editions.each_with_index do |edition, index|
      -if index % 2 == 0
        %tr
      %td
        = f.check_box edition.id, label: edition.nom, id: "fusionner[#{edition.id}]"
    %tr
      %td{colspan: 2}
        = f.submit "Valider", class: "btn"
      

app/views/editions/index.html.haml
%table.table.centree-mini
  - if user_signed_in?
    %tr
      = bootstrap_form_for @edition do |f|
        %td
          = f.text_field :nom, placeholder: "Nouvelle édition",  hide_label: :true
        %td 
          %button.btn.xs.pull-right
            %span.glyphicon.glyphicon-plus
      %td
        = button_to "Fusionner des editions", fusion_editions_path, method: :get, class: "btn pull-right"
  - @editions.each_with_index do |edition, index|
    -if index%2==0
      %tr
    %td{colspan: 2}
      = link_to edition.nom, edition

%br

app/views/editions/show.html.haml
%table.table.centree-mini
  %tr
    %td
      .titre.pull-left
        = @edition.nom
        
      = button_to 'Listes des Editions', editions_path, method: :get, class: "btn pull-right", style: "margin-left: 20px;"
      - if user_signed_in?
        = button_to 'Supprimer', edition_path(@edition), method: :delete, class: "btn pull-right", style: "margin-left: 20px;", data: {confirm: 'Are you sure?' }
        = button_to 'Modifier', edit_edition_path(@edition), method: :get, class: "btn pull-right"

  %tr
    %td
      Livres de cette édition :

  - @liste_by_auteur.each do |auteur, livres|
    %tr
      %td
        %a{href: auteur_path(livres[0].auteur_id)}
          = auteur
        %br
        - livres.each do |livre|
          %a.titre{href: livre_path(livre), style: "margin-left: 40px"}
            = livre.titre
          %br
        
          
  - if @liste_by_auteur.empty?
    %tr
      %td{colspan: 2}
        Aucun livre.
%br
%br