config/routes.rb
Rails.application.routes.draw do
  get 'parametres', to: "parametres#index"
  post 'parametres', to: "parametres#save"

  devise_for :users #, controllers: { sessions: "users/sessions" }
  get 'scans', to: "scans#index"

  resources :livres do
    member do
      get :avatar
      post :avatar, to: :save_avatar
    end
      get ':isbn/get_datas', on: :collection, to: 'livres#get_datas'
  end

  resources :auteurs do
    get :autocomplete_auteur_nom, on: :collection
    get :fusion, on: :collection
    post :fusion, on: :collection, to: :choix_fusion
    post :fusionner, on: :collection
    member do
      get :avatar
      post :avatar, to: :save_avatar
    end
  end

  resources :editions do
    get :autocomplete_edition_nom, on: :collection
    get :fusion, on: :collection
    post :fusion, on: :collection, to: :fusionner
  end

  resources :genres do
    get :autocomplete_genre_nom, on: :collection
    get :fusion, on: :collection
    post :fusion, on: :collection, to: :fusionner
  end

  resources :emplacements do
    get :autocomplete_emplacement_nom, on: :collection
  end

  root 'livres#index'

end

app/models/livre.rb
class Livre < ActiveRecord::Base
  belongs_to :auteur
  belongs_to :edition
  belongs_to :genre
  belongs_to :emplacement
  validates :titre, presence: true
  mount_uploader :couverture, ImageUploader

  def self.search(search)
  if search
    where("LOWER(titre) like LOWER(:search) or LOWER(auteurs.nom) like LOWER(:search) ", search: "%#{search}%").includes(:auteur).references(:auteur)
    # where('name LIKE ?', "%#{search}%")
  else
    # scoped
    all
  end
end

  def auteur_nom
    auteur.nom if auteur
  end

  def auteur_nom=(nom)
    self.auteur = Auteur.find_or_create_by(nom: nom) unless nom.blank?
  end

  def edition_nom
    edition.nom if edition
  end

  def edition_nom=(nom)
    self.edition = Edition.find_or_create_by(nom: nom) unless nom.blank?
  end
  
  def genre_nom
    genre.nom if genre
  end

  def genre_nom=(nom)
    self.genre = Genre.find_or_create_by(nom: nom) unless nom.blank?
  end
  
  def emplacement_nom
    emplacement.nom if emplacement
  end

  def emplacement_nom=(nom)
    self.emplacement = Emplacement.find_or_create_by(nom: nom) unless nom.blank?
  end


end

app/controllers/livres_controller.rb
require 'net/http'

class LivresController < ApplicationController
  before_action :set_livre, only: [:show, :edit, :update, :destroy, :avatar, :save_avatar]
  before_action :set_listes, only: [:show, :edit, :update, :destroy, :create, :new]
  before_action :authenticate_user!, only: [:edit, :update, :destroy, :avatar, :save_avatar, :new]
  before_filter :init
  autocomplete :auteur, :nom, full: true
  autocomplete :edition, :nom, full: true
  autocomplete :genre, :nom, full: true
  autocomplete :emplacement, :nom, full: true
  include ApplicationHelper


  def init
    @title = "Mes Livres"
  end

  def get_datas
    isbn = params[:isbn]

    url = URI.parse("https://www.googleapis.com/books/v1/volumes?country=FR&q=isbn:#{isbn}")
    req = Net::HTTP::Get.new(url.to_s)
    http = Net::HTTP.new(url.host, url.port)
    http.use_ssl = (url.scheme == "https")
    res = http.request(req)
    hash = JSON.parse(res.body)
    if hash["totalItems"] > 0
      id = hash["items"][0]["id"]

      url = URI.parse("https://www.googleapis.com/books/v1/volumes/#{id}?country=FR")
      req = Net::HTTP::Get.new(url.to_s)
      http = Net::HTTP.new(url.host, url.port)
      http.use_ssl = (url.scheme == "https")
      res = http.request(req)
      hash = JSON.parse(res.body)
      datas = hash["volumeInfo"]
      titre_str = datas["title"]
      auteur_str = datas["authors"][0] if datas["authors"].present?
      edition_str = datas["publisher"]
      nbPages = datas["pageCount"].to_i
      description = datas["description"]
      parution = datas["publishedDate"][0..3].to_i
      datas = {found: true, titre: titre_str, auteur: auteur_str, edition: edition_str, 
      parution: parution, nb_pages: nbPages, description: description}
    else
      datas = {found: false}
    end

    render json:  datas
  end

  # GET /livres
  # GET /livres.json
  def index

    # if params[:search]
    #   @livres = Livre.where("LOWER(titre) like LOWER(:search) or LOWER(auteurs.nom) like LOWER(:search) ", search: "%#{params[:search]}%").includes(:auteur).references(:auteur)
    # else
    #   @livres = Livre.all
    # end
    @livres = Livre.search(params[:search]).order(:titre).includes(:auteur, :edition, :genre, :emplacement)
    if params[:page].present?
      session[:livres_pages] = params[:page]
    end
    if @livres.count > cookies[:bookPerPage].to_i
      page = session[:livres_pages]
    end
    @livres = @livres.paginate(page: page, per_page: cookies[:bookPerPage].to_i)

    # @livres = @livres.order(:titre).includes(:auteur, :edition, :genre, :emplacement).paginate( page: page, per_page: cookies[:bookPerPage].to_i)
  end

  # GET /livres/1
  # GET /livres/1.json
  def show
  end

  # GET /livres/new
  def new
    @livre = Livre.new
  end

  # GET /livres/1/edit
  def edit
  end

  # POST /livres
  # POST /livres.json
  def create
    @livre = Livre.new(livre_params)
    if @livre.couverture
      uploader = ImageUploader.new
      uploader.store!(@livre.couverture)
    end

    respond_to do |format|
      if @livre.save
        format.html { redirect_to @livre, notice: 'Livre créé.' }
        format.json { render :show, status: :created, location: @livre }
      else
        format.html { render :new }
        format.json { render json: @livre.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /livres/1
  # PATCH/PUT /livres/1.json
  def update
    respond_to do |format|
      if @livre.update(livre_params)
        format.html { redirect_to @livre, notice: 'Livre modifié' }
        format.json { render :show, status: :ok, location: @livre }
      else
        format.html { render :edit }
        format.json { render json: @livre.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /livres/1
  # DELETE /livres/1.json
  def destroy
    @livre.destroy
    respond_to do |format|
      format.html { redirect_to livres_url, notice: 'Livre supprimé.' }
      format.json { head :no_content }
    end
  end

  def avatar
    @uris = []
    Google::Search::Image.new(:query => "#{@livre.titre} #{@livre.auteur.nom} #{@livre.edition.nom} ").first(8).each do |image|
      @uris.push(image.uri)
    end
  end

  def save_avatar
    filename_image_down = download_image_from_url(params["/livres/#{@livre.id}/avatar"]["uri"])
    File.open(filename_image_down, 'r') do |photo|
      @livre.update(couverture: photo)
      uploader = ImageUploader.new
      uploader.store!(@livre.couverture)
      @livre.save
    end
    File.delete(filename_image_down) if File.exist?(filename_image_down)
    redirect_to livre_url(@livre)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_livre
      @livre = Livre.find(params[:id])
      if @livre.couverture
        uploader = ImageUploader.new
        uploader.retrieve_from_store!(@livre.couverture)
      end
    end

    def set_listes
      @auteurs = Auteur.all.map{|a| [a.nom, a.id]}
      @editions = Edition.all.map{|a| [a.nom, a.id]}
      @genres = Genre.all.map{|a| [a.nom, a.id]}
      @emplacements = Emplacement.all.map{|a| [a.nom, a.id]}
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def livre_params
      params.require(:livre).permit(:isbn, :titre, :auteur_nom, :edition_nom, :genre_nom, :emplacement_nom, :parution, :achat, :couverture, :nb_pages, :description)
    end
end

app/views/livres/_form.html.haml
:javascript
  $(document).ready(function(){
    $("#livre_auteur_nom").autocomplete({
      source: $("#livre_auteur_nom").data('autocomplete-source'),
    });
    $("#livre_edition_nom").autocomplete({
      source: $("#livre_edition_nom").data('autocomplete-source'),
    });
    $("#livre_genre_nom").autocomplete({
      source: $("#livre_genre_nom").data('autocomplete-source'),
    });
    $("#livre_emplacement_nom").autocomplete({
      source: $("#livre_emplacement_nom").data('autocomplete-source'),
    });
  });

= bootstrap_form_for @livre, layout: :horizontal do |f|
  - if @livre.errors.any?
    %div.alert.alert-danger{role: "alert"}
      - @livre.errors.full_messages.each do |msg|
        %li
          %span.glyphicon.glyphicon-exclamation-sign{"aria-hidden" => "true"}
          %span.sr-only
            Error:
          = msg
          
  = f.text_field :titre
  = f.text_field :auteur_nom, label: "Auteur",  data: {autocomplete_source: autocomplete_auteur_nom_auteurs_path}
  = f.text_field :edition_nom, label: "Edition",  data: {autocomplete_source: autocomplete_edition_nom_editions_path}
  = f.text_field :genre_nom, label: "Genre",  data: {autocomplete_source: autocomplete_genre_nom_genres_path}
  = f.text_field :emplacement_nom, label: "Emplacement",  data: {autocomplete_source: autocomplete_emplacement_nom_emplacements_path}
  
  - if @livre.couverture?
    = f.static_control :couverture do
      = link_to image_tag(@livre.couverture_url, class: 'couverture'), avatar_livre_path(@livre)
    = f.file_field :couverture, label: "Modifier"
  - else
    = f.file_field :couverture
    
  = f.number_field :parution
  = f.text_field :achat
  = f.text_area :description, rows: 6
  = f.number_field :nb_pages, label: "Nombre de pages"
  = f.submit 'Sauver', class: "btn"
  %button.btn.pull-right{onclick: 'window.location.href="/";return false;'}
    Retour

app/views/livres/_livres.html.haml
%table.table.small#livres
  - @livres.each_with_index do |livre, index|
    - if index%2==0
      %tr
    %td
      %a{href: livre_path(livre)}
        = image_tag((livre.couverture.blank? ? 'no_image.png' : livre.couverture_url), class: 'couverture')
    %td
      %a.titre{href: livre_path(livre)}
        = livre.titre
      .informations
        - if livre.auteur
          %a{href: auteur_path(livre.auteur)}
            = livre.auteur.nom
        %br
        - if livre.edition
          %a{href: edition_path(livre.edition)}
            = livre.edition.nom
        %br
        - if livre.genre
          = livre.genre.nom
        %br
        = livre.parution
        %br
    


  - if @livres.empty?
    %tr
      %td
        .titre
          - if params[:search]
            Aucun livre ne correspond à la recherche.
          - else
            Aucun livre.
.pull-right
  = will_paginate @livres, :renderer => BootstrapPagination::Rails

app/views/livres/avatar.html.haml
= bootstrap_form_for avatar_livre_path(@livre) do |f|
  %table.table.centree
    %tr
      %td{colspan: 2}
        Choisir une couverture pour 
        = @livre.titre
        \-
        = @livre.auteur.nom
        \-
        = @livre.edition.nom
    - @uris.each_with_index do |uri, index|
      - if index%2==0
        %tr
      %td
        = f.radio_button :uri, uri, label: "", checked: index==0
        = image_tag(uri, class: 'couverture')
    %tr
      %td{colspan: 2}
        = f.submit "Valider", class: "btn"   

app/views/livres/edit.html.haml
.centree
	= render 'form'

app/views/livres/index.html.haml
:javascript
  $(function() {
    $("#search").keyup(function() {
      $.get($("#search").attr("action"), $("#search").serialize(), null, "script");
      return false;
    });
  });
.centree
  %table.table-en-tete{width: "100%"}
    %tr
      %td
        = form_tag(livres_path, :method => "get", class: "navbar-form", id: "search-form") do
          = text_field_tag :search, params[:search], class: "span2", placeholder: "Rechercher un titre"
          %button.btn.xs{type: "submit"}
            %span.glyphicon.glyphicon-search
      %td
        - if user_signed_in?
          = button_to 'Ajouter un Livre', new_livre_path, method: :get, class: "btn pull-right"
  %br
  %br

  %div#livres
    = render 'livres'

app/views/livres/index.js.haml
$("#livres").html("#{escape_javascript(render("livres"))}");

app/views/livres/new.html.haml
:javascript
  $(document).ready(function(){
    $("#search_isbn").click(function(){
      var isbn = $("#livre_isbn").val();
      if (isbn != ""){
        $.ajax({
          url: isbn+"/get_datas",
          beforeSend: function(){
            console.log("avant d'envoyer")
          }

        })
          .done(function( data ) {
            console.log( "Sample of data: ", data );
            if (data["found"]){
              $("#livre_titre").val(data["titre"]);
              $("#livre_auteur_nom").val(data["auteur"]);
              $("#livre_edition_nom").val(data["edition"]);
              $("#livre_parution").val(data["parution"]);
              $("#livre_description").val(data["description"]);
              $("#livre_nb_pages").val(data["nb_pages"]);
            }
            else{
              $('#livre_isbn').popover({content: "ISBN non trouvé."});
              $('#livre_isbn').popover('show');
            }
          });
      }else{
        console.log("nothin !!!")
        $('#livre_isbn').popover({content: "Veuillez rentrer un ISBN."});
        $('#livre_isbn').popover('show');
      }
      return false;
    });
    
    $('#label_isbn').tooltip();

  });


.centree
  %form.form-horizontal
    %div.form-group
      %label.control-label.col-sm-2#label_isbn{for: "livre_isbn", data: {toggle: "tooltip", placement: "right",  trigger: "click", "original-title" => "Tooltip on right", title: "LOL !!!"}}
        ISBN
      %div.col-sm-9
        %input.form-control{id: "livre_isbn", name: "livre[isbn]", type: "text", data: {toggle: "popover", placement: "bottom", trigger: "focus"}}
      %div.col-sm-1
        %button.btn.xs#search_isbn
          %span.glyphicon.glyphicon-search
  = render 'form'

app/views/livres/save.html.haml
%table.table.table-bordered.small#livres_listing
  %thead
    %tr
      %th Titre
      %th Auteur
      %th Edition
      %th Genre
      %th Emplacement
      %th Parution
      %th Achat
      %th
  %tbody
    - @livres.each do |livre|
      %tr
        %td= livre.titre
        %td= livre.auteur.nom if livre.auteur
        %td= livre.edition.nom if livre.edition
        %td= livre.genre.nom if livre.genre
        %td= livre.emplacement.nom if livre.emplacement
        %td= livre.parution
        %td= livre.achat==0 ? nil : livre.achat
        %td
          %button.btn.btn-default.btn-xs{type: "button"}
            %a{href: edit_livre_path(livre)}
              %span.glyphicon.glyphicon-pencil
          %button.btn.btn-default.btn-xs{type: "button"}
            %a{href: livre_path(livre), "data-method" => :delete, "data-confirm" => "Are you sure?"}
              %span.glyphicon.glyphicon-trash

app/views/livres/show.html.haml
%table.centree
  %tr
    %td
      - if @livre.couverture.blank?
        - if user_signed_in?
          = link_to image_tag('no_image.png', class: 'couverture'), avatar_livre_path(@livre)
        - else
          = image_tag('no_image.png', class: 'couverture')
      - else
        = image_tag(@livre.couverture_url, class: 'couverture')
      %br
      %br
    %td
      %a.titre
        = @livre.titre
      .informations
        - if @livre.auteur
          %a{href: auteur_path(@livre.auteur)}
            = @livre.auteur.nom
        %br
        - if @livre.edition
          %a{href: edition_path(@livre.edition)}
            = @livre.edition.nom
        %br
        - if @livre.genre
          -#%a{href: genre_path(@livre.genre)}
          = @livre.genre.nom
        %br
        = @livre.parution
        %br	
        - if  @livre.nb_pages.present?
          = @livre.nb_pages
          pages
        %br
        
      
  %tr
    %td{colspan: 2}
      - if @livre.achat && @livre.achat != "" && @livre.achat != "0"
        Acheté en 
        = @livre.achat
      %br

  - if @livre.emplacement     
    %br
    %tr
      %td{colspan: 2}
        Emplacement :
        %a{href: emplacement_path(@livre.emplacement)}
          = @livre.emplacement.nom
        %br
  - if @livre.description
    %br
    %tr
      %td{colspan: 2}
        Description :
        = @livre.description
        %br
      
  %tr
    %td{colspan: 2}
      = button_to 'Retour', livres_path, method: :get, class: "btn pull-right", style: "margin-left: 30px;"
      - if user_signed_in?
        = button_to 'Supprimer', livre_path(@livre), method: :delete, class: "btn pull-right", style: "margin-left: 20px;", data: {confirm: 'Are you sure?' }
        = button_to 'Modifier', edit_livre_path(@livre), method: :get, class: "btn pull-right"