config/routes.rb
Rails.application.routes.draw do
  get 'parametres', to: "parametres#index"
  post 'parametres', to: "parametres#save"

  devise_for :users #, controllers: { sessions: "users/sessions" }
  get 'scans', to: "scans#index"

  resources :livres do
    member do
      get :avatar
      post :avatar, to: :save_avatar
    end
      get ':isbn/get_datas', on: :collection, to: 'livres#get_datas'
  end

  resources :auteurs do
    get :autocomplete_auteur_nom, on: :collection
    get :fusion, on: :collection
    post :fusion, on: :collection, to: :choix_fusion
    post :fusionner, on: :collection
    member do
      get :avatar
      post :avatar, to: :save_avatar
    end
  end

  resources :editions do
    get :autocomplete_edition_nom, on: :collection
    get :fusion, on: :collection
    post :fusion, on: :collection, to: :fusionner
  end

  resources :genres do
    get :autocomplete_genre_nom, on: :collection
    get :fusion, on: :collection
    post :fusion, on: :collection, to: :fusionner
  end

  resources :emplacements do
    get :autocomplete_emplacement_nom, on: :collection
  end

  root 'livres#index'

end

app/models/auteur.rb
class Auteur < ActiveRecord::Base
	has_many :livres, dependent: :destroy
	validates :nom, presence: true, uniqueness: true
	mount_uploader :photo, ImageUploader
end

app/controllers/auteurs_controller.rb
class AuteursController < ApplicationController
  before_action :set_auteur, only: [:show, :edit, :update, :destroy, :avatar, :save_avatar]
  before_action :authenticate_user!, only: [:edit, :update, :destroy, :avatar, :save_avatar, :new, :fusion, :choix_fusion, :fusionner]
  before_filter :init
  include ApplicationHelper

  def init
    @title = "Auteurs"
  end

  def autocomplete_auteur_nom
    @auteurs = Auteur.order(:nom).where("LOWER(nom) like LOWER(?)", "%#{params[:term]}%")
    respond_to do |format|
      format.html
      format.json { render json: @auteurs.map(&:nom) }
    end
  end

  # GET /auteurs
  # GET /auteurs.json
  def index
    if params[:search]
      @auteurs = Auteur.where("LOWER(nom) like LOWER(?)", "%#{params[:search]}%")
    else
      @auteurs = Auteur.all
    end
    if params[:page].present?
      session[:auteurs_pages] = params[:page]
    end
    if @auteurs.count > cookies[:authorPerPage].to_i
      page = session[:auteurs_pages]
    end 
    @auteurs = @auteurs.order(:nom).paginate( page: page, per_page: cookies[:authorPerPage].to_i)
  end

  # GET /auteurs/1
  # GET /auteurs/1.json
  def show
  end

  # GET /auteurs/new
  def new
    @auteur = Auteur.new
  end

  # GET /auteurs/1/edit
  def edit
  end

  # POST /auteurs
  # POST /auteurs.json
  def create
    @auteur = Auteur.new(auteur_params)
    if @auteur.photo
      uploader = ImageUploader.new
      uploader.store!(@auteur.photo)
    end
    respond_to do |format|
      if @auteur.save
        format.html { redirect_to @auteur, notice: "Auteur #{@auteur.nom} créé." }
        format.json { render :show, status: :created, location: @auteur }
      else
        format.html { render :new }
        format.json { render json: @auteur.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /auteurs/1
  # PATCH/PUT /auteurs/1.json
  def update
    respond_to do |format|
      if @auteur.update(auteur_params)
        format.html { redirect_to @auteur, notice: "Auteur #{@auteur.nom} mis à jour." }
        format.json { render :show, status: :ok, location: @auteur }
      else
        format.html { render :edit }
        format.json { render json: @auteur.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /auteurs/1
  # DELETE /auteurs/1.json
  def destroy
    @auteur.livres.each do |livre|
      livre.auteur_id = nil
      livre.save
    end
    @auteur.delete
    respond_to do |format|
      format.html { redirect_to auteurs_url, notice: "Auteur #{@auteur.nom} détruit." }
      format.json { head :no_content }
    end
  end

  def fusion
    if params[:search]
      @auteurs = Auteur.where("LOWER(nom) like LOWER(?)", "%#{params[:search]}%")
    else
      @auteurs = Auteur.all
    end
    @auteurs = @auteurs.order(:nom)
  end

  def choix_fusion
    liste = params["/auteurs/fusion"].select{|id,bool| bool=="1"}.map{|id,bool| id}
    @auteurs = Auteur.find(liste)
  end

  def fusionner
    id_to_keep = params["/auteurs/fusionner"]["master"]
    params["/auteurs/fusionner"]["ids"].keys.each do |id|
      Livre.where(auteur_id: id).each do |livre|
        livre.auteur_id = id_to_keep
        livre.save
      end
      Auteur.find(id).destroy if id != id_to_keep
    end
    redirect_to auteurs_url, notice: "Fusion effectuée."
  end

  def avatar
    @uris = []
    Google::Search::Image.new(:query => @auteur.nom).first(8).each do |image|
      @uris.push(image.uri)
    end
  end

  def save_avatar
    filename_image_down = download_image_from_url(params["/auteurs/#{@auteur.id}/avatar"]["uri"])
    File.open(filename_image_down, 'r') do |photo|
      @auteur.update(photo: photo)
      uploader = ImageUploader.new
      uploader.store!(@auteur.photo)
      @auteur.save
    end
    File.delete(filename_image_down) if File.exist?(filename_image_down)
    redirect_to auteur_url(@auteur)
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_auteur
      @auteur = Auteur.find(params[:id])
      if @auteur.photo
        uploader = ImageUploader.new
        uploader.retrieve_from_store!(@auteur.photo)
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def auteur_params
      params.require(:auteur).permit(:nom, :photo, :nationalite, :naissance, :mort)
    end
end

app/views/auteurs/_form.html.haml
= bootstrap_form_for @auteur, layout: :horizontal do |f|
  - if @auteur.errors.any?
    #error_explanation
      %h2= "#{pluralize(@auteur.errors.count, "error")} prohibited this auteur from being saved:"
      %ul
        - @auteur.errors.full_messages.each do |msg|
          %li= msg

  = f.text_field :nom
  - if @auteur.photo?
    = f.static_control :photo do
      = image_tag(@auteur.photo_url, class: 'couverture') if @auteur.photo?
    = f.file_field :photo, label: "Modifier"
  - else
    = f.file_field :photo

  = f.text_field :nationalite
  = f.number_field :naissance
  = f.number_field :mort
  = f.submit 'Sauver', class: "btn"
  %button.btn.pull-right{onclick: 'window.location.href="/auteurs";return false;'}
    Retour

app/views/auteurs/avatar.html.haml
= bootstrap_form_for avatar_auteur_path(@auteur) do |f|
  %table.table.centree
    %tr
      %td{colspan: 2}
        Choisir un avatar pour 
        = @auteur.nom
    - @uris.each_with_index do |uri, index|
      - if index%2==0
        %tr
      %td
        = f.radio_button :uri, uri, label: "", checked: index==0
        = image_tag(uri, class: 'couverture')
    %tr
      %td{colspan: 2}
        = f.submit "Valider", class: "btn"
   

app/views/auteurs/choix_fusion.html.haml
= bootstrap_form_for fusionner_auteurs_path, url: fusionner_auteurs_path do |f|
  %table.table.centree
    %tr
      %td{colspan: 3}
        Choisir l'auteur à conserver
    - @auteurs.each_with_index do |auteur, index|
      %tr
        %td
          = f.radio_button :master, auteur.id, label: "", checked: index==0
          = f.hidden_field "ids[#{auteur.id}]"
        %td
          %a{href: auteur_path(auteur)}
            = image_tag((auteur.photo.blank? ? 'no_avatar.jpeg' : auteur.photo_url), class: 'couverture')
        %td
          %a.titre{href: auteur_path(auteur)}
            = auteur.nom
          .informations
            = auteur.naissance
            \-
            = auteur.mort
            %br
            = auteur.nationalite
    %tr
      %td{colspan: 3}
        = f.submit "Valider", class: "btn"
      

app/views/auteurs/edit.html.haml
.centree
  = render 'form'  

app/views/auteurs/fusion.html.haml
%table.table.centree
  %tr
    %td{colspan: 2}
      = form_tag(fusion_auteurs_path, method: :get, class: "navbar-form", id: "search-form") do
        = text_field_tag :search, params[:search], class: "span2", placeholder: "Rechercher un auteur"
        %button.btn.xs{type: "submit"}
          %span.glyphicon.glyphicon-search
  %tr
    %td{colspan: 2}
      Choisir les auteurs à fusionner :
  = bootstrap_form_for(fusion_auteurs_path) do |f|
    - @auteurs.each_with_index do |auteur, index|
      -if index % 2 == 0
        %tr
      %td
        = f.check_box auteur.id, label: auteur.nom, id: "fusionner[#{auteur.id}]"
    %tr
      %td{colspan: 2}
        = f.submit "Valider", class: "btn"
      

app/views/auteurs/index.html.haml
.centree

  %table.table-en-tete{width: "100%"}
    %tr
      %td
        = form_tag(auteurs_path, :method => "get", class: "navbar-form", id: "search-form") do
          = text_field_tag :search, params[:search], class: "span2", placeholder: "Rechercher un auteur"
          %button.btn.xs{type: "submit"}
            %span.glyphicon.glyphicon-search
      %td
        - if user_signed_in?
          = button_to "Fusionner des Auteurs", fusion_auteurs_path, method: :get, class: "btn pull-right", style: "margin-left:10px"
          = button_to 'Ajouter un Auteur', new_auteur_path, method: :get, class: "btn pull-right"
  %br
  %br

  %table.table.small
    - @auteurs.each_with_index do |auteur, index|
      - if index%2==0
        %tr
      %td
        %a{href: auteur_path(auteur)}
          = image_tag((auteur.photo.blank? ? 'no_avatar.jpeg' : auteur.photo_url), class: 'couverture')
      %td
        %a.titre{href: auteur_path(auteur)}
          = auteur.nom
        .informations
          = auteur.naissance
          = auteur.naissance.present? ? "-" : ""
          = auteur.mort
          %br
          = auteur.nationalite
  .pull-right
    = will_paginate @livres, :renderer => BootstrapPagination::Rails

app/views/auteurs/new.html.haml
.centree
	= render 'form'

app/views/auteurs/show.html.haml
%table.centree
  %tr
    %td
      - if @auteur.photo.blank?
        - if user_signed_in?
          = link_to image_tag('no_avatar.jpeg', class: 'couverture'), avatar_auteur_path(@auteur)
        - else
          = image_tag('no_avatar.jpeg', class: 'couverture')
      - else
        = image_tag(@auteur.photo_url, class: 'couverture')
      %br
      %br
    %td
      %a.titre
        = @auteur.nom
      .informations
        = @auteur.naissance
        \-
        = @auteur.mort
        %br
        = @auteur.nationalite
        
  %tr
    %td{colspan: 2}
      = button_to 'Listes des Auteurs', auteurs_path, method: :get, class: "btn pull-right", style: "margin-left: 30px;"
      - if user_signed_in?
        = button_to 'Supprimer', auteur_path(@auteur), method: :delete, class: "btn pull-right", style: "margin-left: 30px;", data: {confirm: 'Are you sure?' }
        = button_to 'Modifier', edit_auteur_path(@auteur), method: :get, class: "btn pull-right"

  %tr
    %td
      %br
      Liste de ses ouvrages :
%br
%table.table.centree
  - @auteur.livres.each do |livre|
    %tr
      %td
        %a{href: livre_path(livre)}
          = image_tag((livre.couverture.blank? ? 'no_image.png' : livre.couverture_url), class: 'couverture')
      %td
        %a.titre{href: livre_path(livre)}
          = livre.titre
        .informations
          - if livre.edition
            %a{href: edition_path(livre.edition)}
              = livre.edition.nom
          %br
          - if livre.genre
            = livre.genre.nom
          %br
          = livre.parution
          %br
          
  - if @auteur.livres.empty?
    %tr
      %td{colspan: 2}
        Aucun livre.
%br
%br